management.endpoints.access.default=none
management.endpoints.web.base-path=
management.endpoints.web.path-mapping.health=/internal/officer-search/scottish-bankrupt-officers/health
management.endpoint.health.show-details=never
management.endpoint.health.access=read_only
